### ISSUE TITLE
Bugs Cuando accedemos a una ruta, carga la misma pero da un fallo con el manejo de errores

### ISSUE THREAD

**Issue by fom78** [alkemyTech/OT172-server#32]
![image](https://user-images.githubusercontent.com/49108644/164943127-4ab261b0-a981-4657-a407-a522d0e76ab0.png)

y en consola:

![image](https://user-images.githubusercontent.com/49108644/164943149-533519b3-c8a0-4fd3-bfe9-2606e55c718c.png)

Asi para todas las rutas, ejemplo con otra:

![image](https://user-images.githubusercontent.com/49108644/164943169-f3afbf90-2be0-468c-a61c-8cb8560503cb.png)

**Comment by fpotichkin** [comment]
El error en console es porq el errorHandler le quiere asignar a res.locals.errors un err.message, pero como el error no tiene message.
 Eso te estaria sobrescribiendo el error real creo, proba consologeando el error antes de esa asignación
