### ISSUE TITLE
Minor error in jwt sign and verify

### ISSUE THREAD

**Issue by fpotichkin** [alkemyTech/OT172-server#36]
En esta llamada se pasan mal los parámetros a la función.
La funcion pide (userId, userEmail), pero recibe un solo objeto conteniendo los 2 parametros necesarios para la funcion, por lo que cuando se ejecute esta funcion, userId = { user.id , user.email } y userEmail va a ser undefined
https://github.com/alkemyTech/OT172-server/blob/14f261944229a42656b5e95019f653fdbbeec574/controllers/authController.js#L20-L23

Esto afecta a la funcion de verificación de jwt .
Donde para tener que acceder al id hay que buscar la propiedad userId dentro de esta
https://github.com/alkemyTech/OT172-server/blob/14f261944229a42656b5e95019f653fdbbeec574/middlewares/validations.js#L15

**Comment by fom78** [comment]
Si es cierto, el otro dia vi algo ue me parecio raro pero segui... hay que arreglarlo.

**Comment by fom78** [comment]
resolved in https://github.com/alkemyTech/OT172-server/pull/38#issue-1213935512
